### ISSUE TITLE
truffle test issue

### ISSUE THREAD

**Issue by bkinsey808** [llSourcell/ethereum_demo#4]
Using truffle 2.0.4 and PR #3, `truffle compile` and `truffle migrate` ran fine but...

```
$ truffle test
[ '0x79b546fc5870eb6839916f59abe40adb5dd1b0ee',
  '0x8b2ea7b6c43c42b9251893b131fe302250166fec',
  '0x12503ce330be3e85bdde0f350921b3216c26ed86',
  '0xefefa1844b3bbc65f0211a5332faca77e772bff6',
  '0xe316094e9fb5ce4ec2e239a039f51604d7aee1ed',
  '0xab0003e658b8bb32e87b8e5d41977ad55fca2ba6',
  '0x941156b8124981ab7cc3b38996054cce5e346c4c',
  '0xce2aa3c0be2cc0d340b1b1244c65aa1d1afc6f57',
  '0xd60f42c30c745881c47b4d60e3fec5bc4026370d',
  '0xe4674b9e2738ab59f3a26c456b8cf3a4ca969574' ]


  Contract: Conference
    1) "before all" hook: prepare suite


  0 passing (244ms)
  1 failing

  1) Contract: Conference "before all" hook: prepare suite:
     Error: VM Exception while processing transaction: out of gas
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/node_modules/ether-pudding/node_modules/web3/lib/web3/errors.js:35:16)
      at /usr/local/lib/node_modules/truffle/node_modules/ether-pudding/node_modules/web3/lib/web3/requestmanager.js:86:36
      at request.onreadystatechange (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:114:13)
      at dispatchEvent (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by llSourcell** [comment]
fixed, pull again :)

**Comment by bkinsey808** [comment]
Thank you I pulled the latest, re-ran compile and migrate, still got the same issue with test, "out of gas"

**Comment by dumebi** [comment]
Hi. Just pulled, have the same issue as well

**Comment by dvigneshwer** [comment]
![image](https://user-images.githubusercontent.com/30098452/31756665-c711d53c-b4c2-11e7-8c8a-b9489b314c8c.png)

Facing the same issue.

**Comment by ankitPagalGuy** [comment]
Facing same issue

**Comment by godfreyhobbs** [comment]
same issue

**Comment by godfreyhobbs** [comment]
The only way I could resolve this issue is with an updated version of truffle.  I used ```npm install truffle@beta```.  I have a PR that is almost complete that fixes test and webapp.

**Comment by dexhunter** [comment]
same issue, setting `testrpc -l <a huge number>` OR change `deployer.deploy(Migrations);`  to ` deployer.deploy(Migrations, {gas: <a large number>});`. ( at `/migrations/1_initial_migration.js`) does not help.

**Comment by pz7** [comment]
The same here with the latest version 4.0.1
Which version is supposed to have fix this? Thanks.

**Comment by godfreyhobbs** [comment]
try truffle@beta also you can try my fork.
