### ISSUE TITLE
truffle serve fails

### ISSUE THREAD

**Issue by kaustav1996** [llSourcell/ethereum_demo#5]
Serving static assets in ./build on port 8080...
Rebuilding...
Error building:

Build configuration can no longer be specified as an object. Please see our documentation for an updated list of supported build configurations.

Build failed. See above.
/usr/local/lib/node_modules/truffle/build/cli.bundled.js:114396
  return (new fsevents(path)).on('fsevent', callback).start();
          ^

TypeError: fsevents is not a constructor
    at createFSEventsInstance (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:114396:11)
    at setFSEventsListener (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:114450:16)
    at FSWatcher.FsEventsHandler._watchWithFsEvents (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:114614:16)
    at FSWatcher.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:114748:25)
    at LOOP (fs.js:1773:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by godfreyhobbs** [comment]
You are using a newer version of truffle. try installing an older version of truffle.

This version requires you to use package.json and npm run dev.  Lots of changes.  I almost have a PR to resolve this.
